#!/bin/bash
x="teste"
menu ()
{
while true $x != "teste"
do
clear
echo -e "\E[44;1;37m            GERENCIAR BADVPN-UDP (PRO)            \E[0m"
    echo ""
    if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
        echo -e "\033[1;37mPORTAS\033[1;37m: \033[1;32m$(netstat -nplt | grep 'badvpn-ud' | awk {'print $4'} | cut -d: -f2 | xargs)"
    else
        sleep 0.1
    fi
    var_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
    echo ""
    echo -e "\033[1;33m \033[1;33m⚠️ INSTALAR BADVPN ANTES DE ABRIR TODAS AS PORTAS ⚠️\033[0m"
    echo ""
    echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mINSTALAR BADVPN(7300 PADRÃO) $var_sks1 \033[0m"
    echo -e "\033[1;31m[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mATIVAR TODAS AS PORTAS BADVPN \033[0m"
    echo -e "\033[1;31m[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mMONITOR DE PORTAS BADVPN-UDP \033[0m"
    echo -e "\033[1;31m[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mVOLTAR \033[0m"
    echo ""
    echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;33m?\033[1;37m "
read x
echo "Opção informada ($x)"
echo "================================================"

case "$x" in


    1)
      badpro
echo "================================================"
;;
    2)
	clear
	echo -e "\033[1;33mPARA SAIR CLICK CTRL + C\033[1;36m"
	apt install wget -y; bash <(wget -qO- raw.githubusercontent.com/piratassh/PR0/main/install.sh)
	sleep 5s
	;;
     3)
        badvpn
echo "================================================"
 ;;
     4)
        menub
echo "================================================"
;;
      0)
menu
echo "================================================"
;;

*)
        echo "Opção inválida!"
esac
done

}
menu
