#!/bin/bash
clear
echo -e "\033[38;5;82mSINCRONIZANDO PAINEL PIRATASSH-PLUS WEB \033[0m"
sleep 4s
apt install wget -y; bash <(wget -qO- https://github.com/piratassh/new2022/raw/main/install/sincpainel.sh)