#!/bin/bash
    clear
    echo -e "\033[46;1;37m                    MENU BADVPN AUTOMATICO                  \033[0m"
    echo -e " \033[47;1;30m ABRIR-BADVPN-DEPOIS ATIVA TODAS A AS PORTAS  \033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➩  \033[42;1;37mATIVAR BAD-VPN\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➩  \033[42;1;37mABRIR TODAS AS PORTAS AUTOMATICO\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 03 •\033[1;34m]\033[1;37m ➩  \033[41;1;37mBADVPN ARM\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➩  \033[1;33mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "\033[01;31m\033[0m"
    echo -e "\033[0;36m░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			badpro
			;;
			2 | 02)
			clear
			apt install wget -y; bash <(wget -qO- raw.githubusercontent.com/piratassh/PR0/main/install.sh)
			;;
			3 | 03)
			badvpn3
			;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			sleep 2
			;;
			esac
		done
	}
	fun_conexao
}
